name: Convert All JSON Files to SRS

on:
  push:
    branches:
      - main
    paths:
      - '*.json'

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: 下载 SingBox 内核
      - name: Download SingBox
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.3/sing-box-1.10.3-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-1.10.3-linux-amd64/sing-box ./sing-box
          chmod +x sing-box

      # Step 3: 转换变更的 JSON 文件
      - name: Convert JSON Files to SRS
        run: |
          # 获取所有发生变更的 JSON 文件
          for json_file in $(git diff --name-only HEAD~1 HEAD | grep '\.json$'); do
            echo "Converting $json_file..."
            srs_file="${json_file%.json}.srs"
            
            # 使用 SingBox 转换
            ./sing-box run -c "$json_file" || { echo "Failed to process $json_file"; exit 1; }
            
            # 重命名并添加到 Git 暂存区
            mv rules.srs "$srs_file"
            git add "$srs_file"
          done

      # Step 4: 提交生成的 SRS 文件
      - name: Commit and Push SRS Files
        run: |
          git config --global user.name "Rictusempra666"
          git config --global user.email "tcmickeyzhou@gmail.com"
          
          # 如果有变更的文件，则提交
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-converted SRS files from JSON"
            git push
          fi
