name: Convert All JSON Files to SRS

on:
  push:
    branches:
      - main
    paths:
      - '*.json'

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: 下载 SingBox 内核
      - name: Download SingBox
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.3/sing-box-1.10.3-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-1.10.3-linux-amd64/sing-box ./sing-box
          chmod +x sing-box

      # Step 3: 转换 JSON 文件
      - name: Convert JSON Files to SRS
        run: |
          for json_file in $(git diff --name-only $(git merge-base HEAD origin/main) HEAD | grep '\.json$'); do
            echo "Processing $json_file..."
            srs_file="${json_file%.json}.srs"
            if [ -f "$json_file" ]; then
              ./sing-box run -c "$json_file" || { echo "Failed to process $json_file"; exit 1; }
              mv rules.srs "$srs_file"
              echo "Generated $srs_file from $json_file"
              git add "$srs_file"
            else
              echo "File $json_file does not exist. Skipping."
            fi
          done

      # Step 4: 提交生成的 SRS 文件
      - name: Commit and Push SRS Files
        run: |
          git config --global user.name "Rictusempra666"
          git config --global user.email "tcmickeyzhou@gmail.com"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-converted SRS files from JSON"
            git push
          fi
